using DomainModel.Classes;
using NUnit.Framework;
using System;

namespace Tests
{
    public class Initializer
    {
        //[Test]
        public void InitializeDb()
        {
            var dbContext = new Persistence.MongoDB.DbContext("mongodb://localhost:27017/firesafe");

            var prodotti = new[]
            {
                new Prodotto() { Prog  =  "5334", CodiceOmol = "MN222A70CD100010", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 1"}, Firma  =  DateTime.Parse ("01-03-1990") ,  Scadenza  = DateTime.Parse ("01-03-2020"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "PRECONTRAINT 1112"},
                new Prodotto() { Prog  =  "11572", CodiceOmol = "MN222A70CD100021", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 1"}, Firma  =  DateTime.Parse ("05-02-1996") ,  Scadenza  = DateTime.Parse ("05-02-2021"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "PRECONTRAINT 552 cl.1."},
                new Prodotto() { Prog  =  "17835", CodiceOmol = "MN222A70CD100054", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 1"}, Firma  =  DateTime.Parse ("13-02-2001") ,  Scadenza  = DateTime.Parse ("13-02-2021"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "TARP PLUS FR 410 (peso totale =410 g/mq)"},
                new Prodotto() { Prog  =  "11048", CodiceOmol = "MN222A70CD100019", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 1"}, Firma  =  DateTime.Parse ("16-06-1995") ,  Scadenza  = DateTime.Parse ("16-06-2020"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "TARP COVER IGNIFUGO"},
                new Prodotto() { Prog  =  "13481", CodiceOmol = "MN222A70CD100033", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 1"}, Firma  =  DateTime.Parse ("21-07-1997") ,  Scadenza  = DateTime.Parse ("21-07-2022"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "SOLTIS 92/1"},
                new Prodotto() { Prog  =  "13219", CodiceOmol = "MN222A70CD200030", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("20-06-1997") ,  Scadenza  = DateTime.Parse ("20-06-2022"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "POLY ADR IGNIFUGO"},
                new Prodotto() { Prog  =  "12897", CodiceOmol = "MN222A70CD200028", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("20-05-1997") ,  Scadenza  = DateTime.Parse ("20-05-2022"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "POLY PANAMA IGNIFUGO"},
                new Prodotto() { Prog  =  "13283", CodiceOmol = "MN222A70CD200032", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("24-06-1997") ,  Scadenza  = DateTime.Parse ("24-06-2022"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "PRECONTRAINT 1202"},
                new Prodotto() { Prog  =  "13356", CodiceOmol = "MN222A70CD200039", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("31-10-1997") ,  Scadenza  = DateTime.Parse ("31-10-2022"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "ISOLINE IGNIFUGO"},
                new Prodotto() { Prog  =  "12501", CodiceOmol = "MN222A70CD200023", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("22-01-1997") ,  Scadenza  = DateTime.Parse ("22-01-2022"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "PRECONTRAINT 1002"},
                new Prodotto() { Prog  =  "13510", CodiceOmol = "MN222A70CD200035", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("28-07-1997") ,  Scadenza  = DateTime.Parse ("28-07-2022"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "POLY RS ADR IGN. CL.2"},
                new Prodotto() { Prog  =  "11662", CodiceOmol = "MN222A70CD200022", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("04-03-1996") ,  Scadenza  = DateTime.Parse ("04-03-2021"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "PRECONTRAINT 1502"},
                new Prodotto() { Prog  =  "5333", CodiceOmol = "MN222A70CD200008", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("16-01-1990") ,  Scadenza  = DateTime.Parse ("16-01-2020"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "602 AUTOMATE"},
                new Prodotto() { Prog  =  "5430", CodiceOmol = "MN222A70CD200009", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("16-01-1990") ,  Scadenza  = DateTime.Parse ("16-01-2020"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "PRECONTRAINT 552/2"},
                new Prodotto() { Prog  =  "2204", CodiceOmol = "MN222A70CD200003", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("06-03-1987") ,  Scadenza  = DateTime.Parse ("06-03-2022"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "PRECONTRAINT 702 M2"},
                new Prodotto() { Prog  =  "9012", CodiceOmol = "MN222A70CD200014", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("06-10-1992") ,  Scadenza  = DateTime.Parse ("06-10-2022"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "PRECONTRAINT 302 TRISTOP"},
                new Prodotto() { Prog  =  "10206", CodiceOmol = "MN222A70CD200018", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("14-03-1994") ,  Scadenza  = DateTime.Parse ("14-03-2019"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "PRECONTRAINT 832"},
                new Prodotto() { Prog  =  "18557", CodiceOmol = "MN222A70CD100056", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("10-04-2002") ,  Scadenza  = DateTime.Parse ("10-04-2022"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "PRINT RS INK JET CL.2."},
                new Prodotto() { Prog  =  "9968", CodiceOmol = "MN222A70CD200015", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("30-11-1993") ,  Scadenza  = DateTime.Parse ("30-11-2023"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "POLY RS IGNIFUGO"},
                new Prodotto() { Prog  =  "19340", CodiceOmol = "EUF1184A70CD200002", Tipo = new Tipo { Nome =  "O"}, Ditta = "DICKSON SAINT-CLAIR S.a.r.l.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("08-05-2002") ,  Scadenza  = DateTime.Parse ("08-05-2022"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "LAC 650 SL"},
                new Prodotto() { Prog  =  "19354", CodiceOmol = "MN222A70D200059", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("22-04-2003") ,  Scadenza  = DateTime.Parse ("22-04-2023"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "POLY LG 530 LAC IGNIFUGO"},
                new Prodotto() { Prog  =  "22942", CodiceOmol = "MI1481A70CD200003", Tipo = new Tipo { Nome =  "O"}, Ditta = "BIANCHI PAOLO S.r.l.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("19-04-2005") ,  Scadenza  = DateTime.Parse ("19-04-2020"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "70 B IGN"},
                new Prodotto() { Prog  =  "26116", CodiceOmol = "MN222A70D200080", Tipo = new Tipo { Nome =  "O"}, Ditta = "F.LLI GIOVANARDI di GIOVANARDI CARLO & C. S.n.c.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("17-07-2008") ,  Scadenza  = DateTime.Parse ("17-07-2023"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "STARPOL FR"},
                new Prodotto() { Prog  =  "22941", CodiceOmol = "MI1481A70CD200002", Tipo = new Tipo { Nome =  "O"}, Ditta = "BIANCHI PAOLO S.r.l.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("19-04-2005") ,  Scadenza  = DateTime.Parse ("19-04-2020"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "CRISTAL BI IGN 75"},
                new Prodotto() { Prog  =  "36265", CodiceOmol = "PD053A70D200063", Tipo = new Tipo { Nome =  "O"}, Ditta = "NAIZIL S.r.l.", Classe = new Classe {Nome = " 2"}, Firma  =  DateTime.Parse ("06-05-2014") ,  Scadenza  = DateTime.Parse ("06-05-2019"),  Impiego  =  "TENDONE",  MacroGruppo  =  "TELI E TENDAGGI",  DenominazioneCommerciale  =  "NAIZIL CAPRI ADR"},
            };

            dbContext.ProdottiCollection.InsertMany(prodotti);

            Assert.Pass();
        }
    }
}
